name: matule
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  easy_localization: ^3.0.7+1
  google_fonts: ^6.2.1
  flutter_zoom_drawer: ^3.2.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
      -  assets/localization/en.json
      -  assets/localization/ru.json
      -  assets/Shoes1.png
      -  assets/Shoes2.png
      -  assets/Shoes3.png
      -  assets/shoes_card.png
      -  assets/bottombar.png
      -  assets/RUS.png
      -  assets/ENG.png
      -  assets/profile.png
      
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  